<Project Sdk="Microsoft.NET.Sdk">
  <!-- host tool, undo the net20 defaults -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultItems>true</EnableDefaultItems>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DefineConstants></DefineConstants>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputPath>$(MSBuildThisFileDirectory)bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="dnlib" Version="4.4.0" />
  </ItemGroup>
</Project>
